done

diff --git a/.github/workflows/npm-grunt.yml b/.github/workflows/npm-grunt.yml
--- a/.github/workflows/npm-grunt.yml
+++ b/.github/workflows/npm-grunt.yml
@@ -17,8 +17,14 @@ jobs:
         run: |
           echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
           echo "VPS_USER: ${{ secrets.VPS_USER }}"
-          echo "VPS_SSH_KEY Length: ${#secrets.VPS_SSH_KEY}"
+          if [[ -z "${{ secrets.VPS_SSH_KEY }}" ]]; then
+            echo "Error: VPS_SSH_KEY is empty!"
+            exit 1
+          else
+            echo "VPS_SSH_KEY is set."
+          fi
         shell: bash
+
 
       - name: Setup SSH key
         run: |
